#include <linux/ioctl.h>

#define RTVM_IOC_MAGIC 0xa5

// ioctl definition
#define RTVM_IOC_RESERVE_TVM_MEM _IOR(RTVM_IOC_MAGIC, 0x00, int)

#define RTVM_IOC_RESERVE_ENCLAVE_MEM _IOR(RTVM_IOC_MAGIC, 0x01, int)

#define RTVM_IOC_CYCLE_BEGIN _IO(RTVM_IOC_MAGIC, 0x02)

#define RTVM_IOC_CYCLE_END _IO(RTVM_IOC_MAGIC, 0x03)

#define POTARA_IOC_CLEAN_SEC_MEM _IO(RTVM_IOC_MAGIC, 0x04)

#define RTVM_IOC_PAGE_REGION_ACCESS _IOR(RTVM_IOC_MAGIC, 0x05, unsigned long)

#define RTVM_IOC_PAGE_REGION_MODIFY _IOR(RTVM_IOC_MAGIC, 0x06, unsigned long)

#define RTVM_IOC_CVM_PRIVATE_MEMORY_ACCESS _IOR(RTVM_IOC_MAGIC, 0x07, unsigned long)

#define RTVM_IOC_CVM_PHYS_MEMORY_ACCESS _IOR(RTVM_IOC_MAGIC, 0x08, unsigned long)

#define RTVM_IOC_CVM_PHYS_MEMORY_MODIFY _IOR(RTVM_IOC_MAGIC, 0x09, unsigned long)
